name: gql_example_cli
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  args: ^2.0.0
  gql: ^1.0.0
  gql_exec: ^1.0.0
  gql_http_link: ^1.0.0
  gql_link: ^1.0.0
dev_dependencies: 
  build_runner: ^2.4.6
  gql_build: ^0.9.0
  gql_pedantic: ^1.0.2
  dart_style: ^2.3.3
dependency_overrides: 
  gql_pedantic: 
    path: ../../gql_pedantic
  gql: 
    path: ../../gql
  gql_exec: 
    path: ../../links/gql_exec
  gql_link: 
    path: ../../links/gql_link
  gql_websocket_link: 
    path: ../../links/gql_websocket_link
  gql_tristate_value: 
    path: ../../codegen/gql_tristate_value
  gql_transform_link: 
    path: ../../links/gql_transform_link
  gql_http_link: 
    path: ../../links/gql_http_link
  gql_error_link: 
    path: ../../links/gql_error_link
  gql_code_builder: 
    path: ../../codegen/gql_code_builder
  gql_build: 
    path: ../../codegen/gql_build
  gql_example_http_auth_link: 
    path: ../gql_example_http_auth_link
  gql_dio_link: 
    path: ../../links/gql_dio_link
  gql_example_dio_link: 
    path: ../gql_example_dio_link
  gql_example_cli_github: 
    path: ../gql_example_cli_github
  gql_example_build: 
    path: ../gql_example_build
  gql_dedupe_link: 
    path: ../../links/gql_dedupe_link
  end_to_end_test_tristate: 
    path: ../../codegen/end_to_end_test_tristate
  end_to_end_test: 
    path: ../../codegen/end_to_end_test
