name: gql_tristate_value
version: 1.0.0
description: A wrapper class for representing a value that can be absent, present and null, or present and non-null.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies: 
  test: ^1.16.8
  lints: ^3.0.0
dependency_overrides: 
  gql_pedantic: 
    path: ../../gql_pedantic
  gql: 
    path: ../../gql
  gql_exec: 
    path: ../../links/gql_exec
  gql_link: 
    path: ../../links/gql_link
  gql_websocket_link: 
    path: ../../links/gql_websocket_link
  gql_transform_link: 
    path: ../../links/gql_transform_link
  gql_http_link: 
    path: ../../links/gql_http_link
  gql_error_link: 
    path: ../../links/gql_error_link
  gql_code_builder: 
    path: ../gql_code_builder
  gql_build: 
    path: ../gql_build
  gql_example_http_auth_link: 
    path: ../../examples/gql_example_http_auth_link
  gql_dio_link: 
    path: ../../links/gql_dio_link
  gql_example_dio_link: 
    path: ../../examples/gql_example_dio_link
  gql_example_cli_github: 
    path: ../../examples/gql_example_cli_github
  gql_example_cli: 
    path: ../../examples/gql_example_cli
  gql_example_build: 
    path: ../../examples/gql_example_build
  gql_dedupe_link: 
    path: ../../links/gql_dedupe_link
  end_to_end_test_tristate: 
    path: ../end_to_end_test_tristate
  end_to_end_test: 
    path: ../end_to_end_test
topics: 
  - graphql
  - gql
  - codegen
