name: gql_dio_link
version: 1.0.1+1
description: Similar to gql_http_link, gql_dio_link is a GQL Terminating Link to execute requests via Dio using JSON
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.13.0 <4.0.0'
dependencies: 
  dio: ^5.2.0+1
  gql: ^1.0.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  meta: ^1.3.0
dev_dependencies: 
  build_runner: ^2.0.0
  code_builder: ^4.2.0
  collection: ^1.15.0
  gql_pedantic: ^1.0.2
  http_parser: ^4.0.0
  mockito: ^5.3.0
  test: ^1.14.3
dependency_overrides: 
  gql_pedantic: 
    path: ../../gql_pedantic
  gql: 
    path: ../../gql
  gql_exec: 
    path: ../gql_exec
  gql_link: 
    path: ../gql_link
  gql_websocket_link: 
    path: ../gql_websocket_link
  gql_tristate_value: 
    path: ../../codegen/gql_tristate_value
  gql_transform_link: 
    path: ../gql_transform_link
  gql_http_link: 
    path: ../gql_http_link
  gql_error_link: 
    path: ../gql_error_link
  gql_code_builder: 
    path: ../../codegen/gql_code_builder
  gql_build: 
    path: ../../codegen/gql_build
  gql_example_http_auth_link: 
    path: ../../examples/gql_example_http_auth_link
  gql_example_dio_link: 
    path: ../../examples/gql_example_dio_link
  gql_example_cli_github: 
    path: ../../examples/gql_example_cli_github
  gql_example_cli: 
    path: ../../examples/gql_example_cli
  gql_example_build: 
    path: ../../examples/gql_example_build
  gql_dedupe_link: 
    path: ../gql_dedupe_link
  end_to_end_test_tristate: 
    path: ../../codegen/end_to_end_test_tristate
  end_to_end_test: 
    path: ../../codegen/end_to_end_test
topics: 
  - graphql
  - gql
  - gql-link
  - dio
